on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing Github actions'
        run: pwd

      - name: 'Printing'
        run: echo Logy

      - name: 'Printing folder contents Before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'Printing folder contents After'
        run: ls

      - name: "Login to Dockerhub"
        run: docker login --username logyshams --password dckr_pat_2UxscNBWHAKL6dE1dWn36kT_8PQ
